#pragma once

enum class NID : std::int8_t
{
	GROUP = 1,
	COLLISION,
	COUNTER,
	TIMER,
	EFFECT,
	COLOR,
	DYNAMIC_COUNTER_TIMER,

#ifdef SPAGHETTDEV_NAMED_EDITOR_GROUPS_EXPORTING
	_INTERNAL_LAST,
	_INTERNAL_TLAST = DYNAMIC_COUNTER_TIMER - 1,
	_INVALID = -1,
	_UNKNOWN = 0
#endif
};
